### ISSUE TITLE
Is this binder going to be supported for Spring Cloud Stream Brooklyn?

### ISSUE THREAD

**Issue by jrgonzalezg** [spring-cloud/spring-cloud-stream-binder-redis#4]
I am fairly new to Spring and i am in the process of implementing my first project. But i am also interested on using / learning the newest Spring reactive APIs. Therefore, i have been trying to implement some functionality by using a RxJava processor, but i have seen the newly released spring-cloud-stream-reactive module and i thought it was a great oportunity to try to use it instead of RxJava. The problem is that my projects were using Redis as the stream binder, and when i switch to using spring-cloud-stream-reactive with the Flux stream listeners, i get errors like this:

Caused by: java.lang.IllegalAccessError: tried to access field org.springframework.cloud.stream.binder.AbstractBinder.evaluationContext from class org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder

Also, the Spring Cloud Stream pages both in GitHub and on spring.io only mention Kafka and RabbitMQ as binder implementations. Does this mean that the new features will not be supported with the Redis binder? Should we switch to Kafka / RabbitMQ or is it expected to work with this binder soon too?

**Comment by mbogoevici** [comment]
Hi @jrgonzalezg,

Sorry for missing your message. 

We have deprecated Redis as a transport and will not maintain a binder for the Brooklyn release. Generally speaking, we haven't found Redis to be reliable as a production messaging system, and we have never recommended using it for other than development.

The Redis binder implementation is not compatible with version 1.1. We should update the README of this project to reflect that.

Please use one of RabbitMQ or Kafka as a binder. 

Thanks,
Marius

**Comment by jrgonzalezg** [comment]
Thanks for the reply!, i will change the binder then. Do you know which of Rabbit MQ or Kafka will be the lighter (less system requirements) replacement for Redis?

**Comment by mbogoevici** [comment]
Both of them are pretty lightweight overall. RabbitMQ would be slightly easier to set up, since you only need to start the server, but Kafka is pretty easy to set up as well. I suggest you use Docker in either case. We use both in our demos.

**Comment by jrgonzalezg** [comment]
It seems that the Docker image for RabbitMQ is an official one, but there is no official one for Kafka although there are 2 popular ones by other parties. Kafka seems to also requires zookeeper which i guess would probably mean additional resources, so i will try RabbitMQ first then. Thanks!
